### ISSUE TITLE
Bad link in readme

### ISSUE THREAD

**Issue by jhirbour** [alexdean/app_status#4]
The link in the readme to http://kramdown.gettalong.org/quickref.html returns "The service is not available. Please try again later." 

I think the link should point to : https://kramdown.gettalong.org/quickref.html , but I'm not sure what it pointed to previously.

**Comment by danbernier** [comment]
`kramdown` [was removed](https://github.com/alexdean/app_status/pull/3/files#diff-674ec06ac70777e8cd01115a0e981faaL1) in v2.0, so maybe we should just remove this part from the README?
